# Generated by Django 4.2 on 2024-05-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
