# Generated by Django 4.2 on 2024-05-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_community_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('motivation', models.TextField(null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
            ],
        ),
    ]
