# Generated by Django 4.2 on 2024-06-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_communityhabit_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityhabit',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
